
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEF END ID INC INT LP MOVE REG REPEAT RPprog : instr \n            | instr proginstr : cmd \n             | macdefcmd : incr \n           | mv \n           | rpt \n           | macincr : INC REGmv : REG MOVE REG \n          | REG MOVE INTrpt : REPEAT REG bodybody : innerbody ENDinnerbody : cmd \n                 | cmd innerbodymac : REG MOVE ID reglistmacdef : DEF ID reglist bodyinnerreglist : REG \n                    | REG innerreglistreglist : LP innerreglist RP '
    
_lr_action_items = {'INC':([0,3,4,5,7,9,10,11,14,16,19,20,22,23,24,26,27,29,33,],[8,-5,8,-8,-3,-4,-7,-6,8,-9,-11,-10,-12,8,8,-16,-13,-17,-20,]),'ID':([12,13,],[17,18,]),'$end':([3,4,5,6,7,9,10,11,15,16,19,20,22,26,27,29,33,],[-5,-1,-8,0,-3,-4,-7,-6,-2,-9,-11,-10,-12,-16,-13,-17,-20,]),'REG':([0,2,3,4,5,7,8,9,10,11,13,14,16,19,20,22,23,24,25,26,27,29,30,33,],[1,14,-5,1,-8,-3,16,-4,-7,-6,20,1,-9,-11,-10,-12,1,1,30,-16,-13,-17,30,-20,]),'REPEAT':([0,3,4,5,7,9,10,11,14,16,19,20,22,23,24,26,27,29,33,],[2,-5,2,-8,-3,-4,-7,-6,2,-9,-11,-10,-12,2,2,-16,-13,-17,-20,]),'END':([3,5,10,11,16,19,20,21,22,23,26,27,28,33,],[-5,-8,-7,-6,-9,-11,-10,27,-12,-14,-16,-13,-15,-20,]),'RP':([30,31,32,],[-18,33,-19,]),'DEF':([0,3,4,5,7,9,10,11,16,19,20,22,26,27,29,33,],[12,-5,12,-8,-3,-4,-7,-6,-9,-11,-10,-12,-16,-13,-17,-20,]),'LP':([17,18,],[25,25,]),'INT':([13,],[19,]),'MOVE':([1,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instr':([0,4,],[4,4,]),'innerreglist':([25,30,],[31,32,]),'mac':([0,4,14,23,24,],[5,5,5,5,5,]),'innerbody':([14,23,24,],[21,28,21,]),'reglist':([17,18,],[24,26,]),'body':([14,24,],[22,29,]),'prog':([0,4,],[6,15,]),'cmd':([0,4,14,23,24,],[7,7,23,23,23,]),'macdef':([0,4,],[9,9,]),'rpt':([0,4,14,23,24,],[10,10,10,10,10,]),'mv':([0,4,14,23,24,],[11,11,11,11,11,]),'incr':([0,4,14,23,24,],[3,3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> instr','prog',1,'p_prog','rpt_syntax.py',97),
  ('prog -> instr prog','prog',2,'p_prog','rpt_syntax.py',98),
  ('instr -> cmd','instr',1,'p_instr','rpt_syntax.py',105),
  ('instr -> macdef','instr',1,'p_instr','rpt_syntax.py',106),
  ('cmd -> incr','cmd',1,'p_cmd','rpt_syntax.py',110),
  ('cmd -> mv','cmd',1,'p_cmd','rpt_syntax.py',111),
  ('cmd -> rpt','cmd',1,'p_cmd','rpt_syntax.py',112),
  ('cmd -> mac','cmd',1,'p_cmd','rpt_syntax.py',113),
  ('incr -> INC REG','incr',2,'p_incr','rpt_syntax.py',117),
  ('mv -> REG MOVE REG','mv',3,'p_mv','rpt_syntax.py',121),
  ('mv -> REG MOVE INT','mv',3,'p_mv','rpt_syntax.py',122),
  ('rpt -> REPEAT REG body','rpt',3,'p_rpt','rpt_syntax.py',126),
  ('body -> innerbody END','body',2,'p_body','rpt_syntax.py',130),
  ('innerbody -> cmd','innerbody',1,'p_innerbody','rpt_syntax.py',134),
  ('innerbody -> cmd innerbody','innerbody',2,'p_innerbody','rpt_syntax.py',135),
  ('mac -> REG MOVE ID reglist','mac',4,'p_mac','rpt_syntax.py',143),
  ('macdef -> DEF ID reglist body','macdef',4,'p_macdef','rpt_syntax.py',148),
  ('innerreglist -> REG','innerreglist',1,'p_innerreglist','rpt_syntax.py',152),
  ('innerreglist -> REG innerreglist','innerreglist',2,'p_innerreglist','rpt_syntax.py',153),
  ('reglist -> LP innerreglist RP','reglist',3,'p_reglist','rpt_syntax.py',160),
]
